name: pytorch_gradcam_anim
channels:
  - defaults
  # - conda-forge
dependencies:
  - python=3.10.4
  - pip
  - pip:
      - numpy
      - Pillow
      - torch>=1.7.1
      - torchvision>=0.8.2
      - ttach
      - tqdm
      - opencv-python
      - matplotlib
      - scikit-learn